### ISSUE TITLE
Is this works with Nuxt Universal Mode

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [aminoeditor/vue-ace#4]

**Comment by ericuldall** [comment]
I'm not sure if this works with Nuxt Universal mode. Have you tried it?
We're currently using it in webpack builds and haven't tested it with Nuxt.

**Comment by rahulkumarsingh73690** [comment]
> I'm not sure if this works with Nuxt Universal mode. Have you tried it?
> We're currently using it in webpack builds and haven't tested it with Nuxt.

Yes, I tried. This doesn't work :(

**Comment by ericuldall** [comment]
Can you send some info on how to reproduce your setup so I can test locally? Did you use vue.cli and just select Nuxt? Did you build from scratch?

**Comment by rahulkumarsingh73690** [comment]
I tested on Nuxt SSR mode
